name = "comn-setelite"
main = "src/index.js"
compatibility_date = "2026-09-20"

[[durable_objects.bindings]]
name = 'neuro-v8'
class_name = "NeuroSyncRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["NeuroSyncRoom"]
