name = "neuro-v8"
main = "src/worker.js"
compatibility_date = "2026-09-20"

[assets]
directory = "./public"
binding = "ASSETS"

[durable_objects]
bindings = [{ name = "Neuro-8", class_name = "Neuro-8" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Neuro-8"]
