# ...
[[unsafe.bindings]]
name = "Neuro_8"
type = "durable_object_namespace"
class_name = "NeuroSyncRoom"
namespace_id = "a8bb6f32e5914b688a35d0bcc3fd7a21"

[[unsafe.bindings]]
name = "NEURO_ROOM"
type = "durable_object_namespace"
class_name = "NeuroSyncRoom"
namespace_id = "a8bb6f32e5914b688a35d0bcc3fd7a21"
